import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<body>
				<div className="flex flex-col min-h-screen">
					<Navigation />
					<main className="flex-1 container max-w-screen-xl mx-auto px-5 py-10">
						{children}
					</main>
					<footer className="py-5 border-t">
						<div className="text-center text-sm text-gray-500">Coryright</div>
					</footer>
				</div>
			</body>
		</html>
	);
}
